#!/bin/bash
#####PROTOKODS
: << 'END'
name1=kartupelis
echo "File Name: $0"
echo "First Parameter : $1"
echo "Second Parameter : $2"
echo "Quoted Values: $@"
echo "Quoted Values 2: $*"
echo "Total Number of Parameters : $#"
echo "procesa numurs:$$"
##2.Piemers/3.Piemers
#readonly name1 #scripts variable pieskir read only ipasibu
#unset name1    #scripts variable vertibu izdzesh, ja readonly tad nevares
echo $name1
END

####https://www.tutorialspoint.com/unix/unix-basic-operators.htm
###: << ''END iekš apastrofiem
: << 'END'

##Aritmētiskie
# var lietot a=10,b=69 un tad piesauc ar $a un $b
echo "Addition" #+
valadd=`expr 5 + 3`
echo $valadd
echo "Subtraction" #-
valsub=`expr 5 - 3`
echo $valsub
echo "Multiplication" #\*
valmul=`expr 5  \* 3`
echo $valmul
echo "Division" #/
valdiv=`expr 5 / 3`
echo $valdiv
echo "Modulus" #%
valmod=`expr 5 % 3`
echo $valmod
echo "Assignment" #=
valass=`expr 5 = 3`
echo $valass
echo "Equality" #==
if [ 6 == 4 ]
then echo true
else echo false
fi
echo "Not Equality" #!=
if [ 6 != 4 ]
then echo true
else echo false
fi
END

##Argumenta ievade
#$1,$2 - 1. un 2. arguments caur ievadi
a=$1
b=$2
valadd=`expr $a + $b`
echo "$a+$b=" $valadd
