#!/bin/bash
#####PROTOKODS
: << 'END'
name1=kartupelis
echo "File Name: $0"
echo "First Parameter : $1"
echo "Second Parameter : $2"
echo "Quoted Values: $@"
echo "Quoted Values 2: $*"
echo "Total Number of Parameters : $#"
echo "procesa numurs:$$"
##2.Piemers/3.Piemers
#readonly name1 #scripts variable pieskir read only ipasibu
#unset name1    #scripts variable vertibu izdzesh, ja readonly tad nevares
echo $name1
END

####https://www.tutorialspoint.com/unix/unix-basic-operators.htm
###: << ''END iekš apastrofiem

##Operācijas ar argumentiem
# var lietot a=10,b=69 un tad piesauc ar $a un $b
#: << 'END'
if [ $# == 2 ]
then
a=$1
b=$2
echo "Addition" #+
valadd=`expr $a + $b`
echo $valadd
echo "Subtraction" #-
valsub=`expr $a - $b`
echo $valsub
echo "Multiplication" #\*
valmul=`expr $a  \* $b`
echo $valmul
echo "Division" #/
valdiv=`expr $a / $b`
echo $valdiv
echo "Modulus" #%
valmod=`expr $a % $b`
echo $valmod
echo "Assignment" #=
valass=`expr $a = $b`
echo $valass
fi
echo "Equality" #==
 if [ 6 == 4 ]
  then echo true
  else echo false
 fi
echo "Not Equality" #!=
if [ 6 != 4 ]
then echo true
else echo false
fi
#END

##Argumenta ievade
: <<'END'
#$1,$2 - 1. un 2. arguments caur ievadi
a=$1
b=$2
valadd=`expr $a + $b`
echo "$a+$b=$valadd"
END
