#!/bin/bash
name1=kartupelis
##4.Piemers

echo "File Name: $0"
echo "First Parameter : $1"
echo "Second Parameter : $2"
echo "Quoted Values: $@"
echo "Quoted Values 2: $*"
echo "Total Number of Parameters : $#"
echo "procesa numurs:$$"
##2.Piemers/3.Piemers
#readonly name1 #scripts variable pieskir read only ipasibu
#unset name1    #scripts variable vertibu izdzesh, ja readonly tad nevares
echo $name1
