#!/usr/bin/python
#-*- coding: utf-8 -*-

# Importējam nepieciešamos moduļus.
import random
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt

# Definējam savu funkciju
def my_atan(x):
    a=1
    S=a
    k=1
    for i in range(500):
        R=((2*k)*(2*k-1)/(k**2*2**2*((2*k+1)/(2*k-1))))*((x**2)/(1+x**2))
        a=a*R
        S=S+a
        k=k+1
    s=x/sqrt(1+x**2)*S
    return s

N =20000
x = []
y = []
a = 0.
b = 4#np.pi
c = -4.
d = 4.

for i in range(N):
    x.append(random.uniform(a,b))
for i in range(N):
    y.append(random.uniform(c,d))
red_x = []
red_y = []
green_x = []
green_y = []

for i in range(N):
    if (y[i] < my_atan(x[i]) and y[i] > 0) or (y[i] > my_atan(x[i]) and y[i] < 0):
        green_x.append(x[i])
        green_y.append(y[i])
    else:
        red_x.append(x[i])
        red_y.append(y[i])
print("zimesana")
plt.plot(green_x,green_y,'go')
plt.plot(red_x,red_y,'rv')
plt.grid()
plt.show()

areaRect = (b-a)*(d-c)
areaFunc = areaRect * len(green_x) / N
print(areaFunc)
