#!/usr/bin/python
#-*- coding: utf-8 -*-

# Sasveicināmies un iegūstam datus!
print("Programma izveidos dalījumu tabulu jūsu izvēlētam skaitlim un nākamajiem desmit skaitļiem!")
a=eval(input("Lietotāj, ievadiet skaitli!\n"))
print("Jūs ievadījāt skaitli {}, kura datu tips ir {}!".format(a,type(a)))

# Izveidojam tabulas nosaukumu un aprakstošos lielumus!
print()
print("{:*^{width}}".format('Dalījumu tabula',width=(len(str(a))+59)))
print("{}".format((len(str(a)))*' '+2*' '),end='')
m=1
for i in range(10):
    print(m,end='%    ')    
    m=m+1
print()

# Izveidosim dalījumu tabulu ar 2 ciklu palīdzību
import numpy as np
x=np.arange(a,a+10)
maxi=np.amax(x)
for i in range(10):
    print("{:{width}}".format(a,width=len(str(maxi))),end=' ')
    n=1
    for i in range(10):
        print("{}".format(a%n),end='     ')
        n=n+1
    a=a+1
    print()
