#!/bin/bash

# Pastāstam, ko veic programma un iegustam datus.
echo -e "Lietotāj, ievadiet veselus skaitļus un tiks izvadīta:!"
echo 1. minimālā vērtība
echo 2. maksimālā vērtība
echo 3. vidējā vērtība
echo 4. sakārtota virkne
echo 5. mediāna
echo 6. moda
A=("$@")
elements=$#
echo jūsu $elements vērtības veido skaitļu masīvu a=[$@]
echo
 
# Vispirms sakārtosim masīvu augošā secībā!
for (( i=0; i < $elements; i++ )); do
for (( j=$i; j < $elements; j++ )); do
if (( ${A[i]} > ${A[j]} )); then
t=${A[i]}
A[i]=${A[j]}
A[j]=$t
fi
done
done

# Aprēķinām vidējo vērtību
sum=0
for (( i=0; i < $elements; i++ )); do
sum=`expr $sum + ${A[i]}` 
done
vid=`expr $sum / $elements`

# Aprēķināsim medianu
if (( $elements % 2 == 0 )); then
step=`expr ${A[$elements / 2]} + ${A[$elements / 2 - 1]}`
median=`expr $step / 2`
else
median=${A[`expr $elements / 2`]}
fi

# Apreķinām modu
for (( i=0; i < $elements; i++ )); do
for (( j=$i; j < $elements; j++ )); do
if (( ${A[i]} == ${A[j]} )); then
${A[i]}array+=${A[i]}

# Izvadīsim, ko lietotajs vēlas
echo 1. ${A[0]}
echo 2. ${A[$elements - 1]}
echo 3. $vid
echo 4. ${A[@]}
echo 5. $median japiemin, ka bash nestrādā ar komatu, tādēļ ja vēlaties precizitāti ar komatu, jāpiesauc ārējais modulis.
