#!/usr/bin/python
#-*- coding: utf-8 -*-

print("Lietotāj, ievadi skaitli un programma izveidos dalījumu tabulu nākamajiem desmit skaitļiem!")
a=eval(input("Lietotāj, ievadiet skaitli!\n"))
b=type(a)
print("Jūs ievadījāt skaitli %s, kura datu tips ir %s\n"%(a,b))
#atstarpe=' '*digit #lai tabulas iedaļa, kas rāda lietotāja izvēlētos skaitļus nobīdītu tabulu un neizraisītu jukas
v=0
while v<=10:
    if len(str(a))!=len(str(a+1)):
        cipari=len(str(a+1))
    else:
            cipari=len(str(a))
    a=a+1
    v=v+1
atstarpe=' '*cipari
print("%s"%(atstarpe), end=' ')
print("%1     %2     %3     %4     %5     %6     %7     %8     %9     %10")
r=0
while r<=10:
    print("%d"%(a), end=' ')
    k=1 #kollonas kārtas skaitlis
    n=1 #pirmais dalītājs
    while k<=10: #kolonnu skaits
        print("%d     "%(a%n), end=' ')
        n=n+1 #skaitlis ar ko dal
        k=k+1
    r=r+1
    a=a+1
    print()
